Repository ku-cse-grad-proj/AIew, pull requests merged in 2025-07, with the labels that each got.

#9 [AIEW-26] CORS 설정과 로그인 흐름 확립
  .github/PULL_REQUEST_TEMPLATE.md
  apps/core-api/.env.example
  apps/core-api/package.json
  apps/core-api/src/plugins/githubOAuth2.ts
  apps/core-api/src/plugins/googleOAuth2.ts
  apps/core-api/src/plugins/jwt.ts
  apps/core-api/src/routes/api/me.ts
  apps/core-api/src/routes/auth/refresh.ts
  apps/core-api/src/server.ts
  pnpm-lock.yaml
Labels: enhancement

#10 [AIEW-28] API 공유를 위한 Swagger 셋업
  apps/core-api/package.json
  apps/core-api/src/app.ts
  apps/core-api/src/configs/swaggerOption.ts
  apps/core-api/src/configs/swaggerUiOption.ts
  apps/core-api/src/plugins/githubOAuth2.ts
  apps/core-api/src/plugins/googleOAuth2.ts
  apps/core-api/src/plugins/jwt.ts
  apps/core-api/src/plugins/sharedSchemas.ts
  apps/core-api/src/routes/api/me.ts
  apps/core-api/src/routes/auth/refresh.ts
  apps/core-api/src/routes/example/index.ts
  apps/core-api/src/routes/ping.ts
  apps/core-api/src/routes/root.ts
  apps/core-api/src/schemas/error.ts
  apps/core-api/src/schemas/index.ts
  apps/core-api/src/schemas/interface.ts
  apps/core-api/src/schemas/user.ts
  apps/core-api/src/server.ts
  apps/core-api/src/utils/schemaId.ts
  apps/web-client/package.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#13 [AIEW-35] 스키마 폴더 구조 변경 및 웹소켓 메시지 인터페이스 정의
  apps/core-api/src/plugins/sharedSchemas.ts
  apps/core-api/src/schemas/rest/error.ts
  apps/core-api/src/schemas/rest/index.ts
  apps/core-api/src/schemas/rest/interface.ts
  apps/core-api/src/schemas/rest/user.ts
  apps/core-api/src/schemas/ws/interview.dto.ts
Labels: Backend

#14 [AIEW-36] Swagger에 등록할 가짜 REST endpoint 생성
  apps/core-api/src/configs/swaggerOption.ts
  apps/core-api/src/plugins/sharedSchemas.ts
  apps/core-api/src/routes/docs/websocket.ts
  apps/core-api/src/schemas/ws/index.ts
  apps/core-api/src/schemas/ws/interview.dto.ts
  apps/core-api/src/utils/schemaId.ts
Labels: documentation, backend

#16 Aiew 30 backedn login api 연결
  apps/web-client/src/app/auth/callback/route.ts
  apps/web-client/src/app/dashboard/_component/Header.tsx
  apps/web-client/src/app/dashboard/layout.tsx
  apps/web-client/src/app/dashboard/page.tsx
  apps/web-client/src/app/lib/fetch.ts
  apps/web-client/src/app/login/component/LoginButton.tsx
  apps/web-client/src/app/login/page.tsx
  apps/web-client/src/middleware.ts
Labels: frontend
