Repository ku-cse-grad-proj/AIew, pull requests merged in 2025-08, with the labels that each got.

#19 [AIEW-41] 텍스트 전처리
  apps/ai-server/app/api/v1/endpoints/pdf.py
  apps/ai-server/app/services/preprocessor.py
  apps/ai-server/poetry.lock
  apps/ai-server/pyproject.toml
Labels: ai

#20 [AIEW-43] route prefix 적용
  .github/workflows/ci.yml
  apps/core-api/package.json
  apps/core-api/src/app.ts
  apps/core-api/src/plugins/githubOAuth2.ts
  apps/core-api/src/plugins/googleOAuth2.ts
  apps/core-api/src/routes/README.md
  apps/core-api/src/routes/api/v1/interviews/index.ts
  apps/core-api/src/routes/api/v1/me/index.ts
  apps/core-api/src/routes/api/v1/refresh/index.ts
  apps/core-api/src/routes/docs/websocket-guide/index.ts
  apps/core-api/src/routes/example/index.ts
  apps/core-api/src/routes/ping.ts
  apps/core-api/src/routes/root.ts
  apps/core-api/test/helper.ts
  apps/core-api/test/routes/api/v1/me.test.ts
  apps/core-api/test/routes/example.test.ts
  apps/core-api/test/routes/root.test.ts
  package.json
Labels: backend

#21 [AIEW-44] OAuth 과정에서 프로필 사진 받아오기
  .github/PULL_REQUEST_TEMPLATE.md
  apps/core-api/nodemon.json
  apps/core-api/package.json
  apps/core-api/prisma/migrations/20250802085416_add_pic_url/migration.sql
  apps/core-api/prisma/schema.prisma
  apps/core-api/src/configs/swaggerOption.ts
  apps/core-api/src/plugins/githubOAuth2.ts
  apps/core-api/src/plugins/googleOAuth2.ts
  apps/core-api/src/plugins/sharedSchemas.ts
  apps/core-api/src/routes/api/v1/interviews/index.ts
  apps/core-api/src/routes/api/v1/me/index.ts
  apps/core-api/src/routes/api/v1/refresh/index.ts
  apps/core-api/src/routes/docs/websocket-guide/index.ts
  apps/core-api/src/routes/warning/user/delete/index.ts
  apps/core-api/src/schemas/rest/error.ts
  apps/core-api/src/schemas/rest/user.ts
  apps/core-api/src/schemas/ws/interview.dto.ts
  apps/core-api/test/tsconfig.json
  apps/core-api/tsconfig.json
  pnpm-lock.yaml
Labels: backend

#23 [AIEW-31] GET 면접 정보(들)
  apps/core-api/prisma/migrations/20250805082701_add_current_question_index/migration.sql
  apps/core-api/prisma/schema.prisma
  apps/core-api/src/routes/api/v1/interviews/_sessionId/index.ts
  apps/core-api/src/routes/api/v1/interviews/create/index.ts
  apps/core-api/src/routes/api/v1/interviews/index.ts
  apps/core-api/src/schemas/rest/index.ts
  apps/core-api/src/schemas/rest/interview.ts
  apps/core-api/src/server.ts
  apps/core-api/src/utils/schemaId.ts
Labels: backend

#24 refactor(web-client): 변경된 api 반영
  apps/web-client/src/app/dashboard/_component/Header.tsx
  apps/web-client/src/app/lib/fetch.ts
  apps/web-client/src/app/login/component/LoginButton.tsx
  apps/web-client/src/middleware.ts
Labels: frontend

#33 [AIEW-53] 답변 DB 스키마 구성
  apps/core-api/prisma/migrations/20250812025640_add_interview_step/migration.sql
  apps/core-api/prisma/migrations/20250823105018_add_detailed_evaluation_fields/migration.sql
  apps/core-api/prisma/schema.prisma
  apps/core-api/src/plugins/socket.ts
  apps/core-api/src/routes/api/v1/interviews/create/index.ts
  apps/core-api/src/schemas/rest/error.ts
  apps/core-api/src/schemas/ws/interview.dto.ts
Labels: backend

#38 AIEW 63 면접 대기 화면
  apps/web-client/src/app/globals.css
  apps/web-client/src/app/hooks/useInterviewSocket.ts
  apps/web-client/src/app/interview/_components/Card.tsx
  apps/web-client/src/app/interview/_components/FooterButtons.tsx
  apps/web-client/src/app/interview/create/Form.tsx
  apps/web-client/src/app/interview/create/action.ts
  apps/web-client/src/app/interview/waiting/[sessionId]/components/InfoItem.tsx
  apps/web-client/src/app/interview/waiting/[sessionId]/components/LoadingCard.tsx
  apps/web-client/src/app/interview/waiting/[sessionId]/components/LoadingCircle.tsx
  apps/web-client/src/app/interview/waiting/[sessionId]/page.tsx
  apps/web-client/src/app/lib/socket.ts
  apps/web-client/tsconfig.json
  apps/web-client/types/interview-types.d.ts
Labels: frontend

#41 [AIEW-67] 파일 업로드 크기 제한
  apps/core-api/src/server.ts
Labels: backend

#46 [AIEW-71] Next.js에서 OpenAI와 WebRTC 연결할 때 필요한 임시 토큰 발급
  apps/core-api/.env.example
  apps/core-api/package.json
  apps/core-api/src/routes/api/v1/interviews/_sessionId/stt-token/index.ts
  apps/core-api/src/schemas/rest/error.ts
  apps/core-api/src/schemas/rest/index.ts
  apps/core-api/src/schemas/rest/interface.ts
  apps/core-api/src/schemas/rest/interview.ts
  apps/core-api/src/schemas/rest/user.ts
  apps/core-api/src/server.ts
  apps/core-api/test/helper.ts
  apps/core-api/test/routes/api/v1/me.test.ts
  pnpm-lock.yaml
Labels: backend
