Repository ku-cse-grad-proj/AIew, pull requests merged in 2025-09, with the labels that each got.

#50 [AIEW-73] 인터뷰 흐름 구현
  .github/workflows/ci.yml
  apps/core-api/package.json
  apps/core-api/prisma/migrations/20250831072159_add_ai_question_id/migration.sql
  apps/core-api/prisma/schema.prisma
  apps/core-api/src/plugins/services/ai-client.ts
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/plugins/socket.ts
  apps/core-api/src/types/ai.types.ts
  apps/core-api/test/helper.ts
  apps/core-api/test/routes/ws/interview.test.ts
  pnpm-lock.yaml
Labels: backend

#51 Aiew 78 interview page 구현
  apps/web-client/package.json
  apps/web-client/public/icons/arrow_back.svg
  apps/web-client/public/icons/arrow_forward.svg
  apps/web-client/public/icons/delete.svg
  apps/web-client/public/icons/edit.svg
  apps/web-client/src/app/(main)/_components/Header.tsx
  apps/web-client/src/app/(main)/_components/MainLink.tsx
  apps/web-client/src/app/(main)/_components/Nav.tsx
  apps/web-client/src/app/(main)/interview/_components/Card.tsx
  apps/web-client/src/app/(main)/interview/_components/Carousel.tsx
  apps/web-client/src/app/(main)/interview/_components/FooterButtons.tsx
  apps/web-client/src/app/(main)/interview/_components/InterviewCard.tsx
  apps/web-client/src/app/(main)/interview/page.tsx
  apps/web-client/src/app/(main)/layout.tsx
  apps/web-client/src/app/globals.css
  apps/web-client/src/app/hooks/EmblaCarouselArrowButtons.tsx
  apps/web-client/src/app/hooks/EmblaCarouselDotButton.tsx
  apps/web-client/src/app/layout.tsx
  pnpm-lock.yaml
Labels: frontend

#58 [AIEW-81] InterviewSession CRUD
  apps/core-api/package.json
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/routes/api/v1/interviews/_sessionId/index.ts
  apps/core-api/src/routes/api/v1/interviews/create/index.ts
  apps/core-api/src/routes/api/v1/interviews/index.ts
  apps/core-api/src/routes/api/v1/users/_userId/index.ts
  apps/core-api/src/routes/docs/websocket-guide/index.ts
  apps/core-api/src/schemas/rest/interview.ts
  apps/core-api/src/utils/schemaId.ts
  apps/core-api/test/helper.ts
  apps/core-api/test/plugins/support.test.ts
  apps/core-api/test/routes/api/v1/interviews.test.ts
  apps/core-api/test/routes/api/v1/me.test.ts
  apps/core-api/test/routes/api/v1/users.test.ts
  apps/core-api/test/routes/ws/interview.test.ts
  apps/core-api/test/routes/ws/interview.ws.test.ts
  apps/core-api/test/services/interview.service.test.ts
  apps/core-api/test/tsconfig.json
  apps/web-client/src/app/(main)/interview/create/action.ts
  pnpm-lock.yaml
Labels: backend

#57 [AIEW-51] stt 서비스 연결
  apps/core-api/src/routes/api/v1/interviews/_sessionId/stt-token/index.ts
  apps/web-client/package.json
  apps/web-client/src/app/(main)/interview/stt/[sessionId]/_components/Button.jsx
  apps/web-client/src/app/(main)/interview/stt/[sessionId]/_components/EventLog.jsx
  apps/web-client/src/app/(main)/interview/stt/[sessionId]/_components/SessionControls.jsx
  apps/web-client/src/app/(main)/interview/stt/[sessionId]/_components/Stt.tsx
  apps/web-client/src/app/(main)/interview/stt/[sessionId]/page.tsx
  apps/web-client/src/app/(main)/interview/waiting/[sessionId]/page.tsx
  apps/web-client/src/app/(main)/layout.tsx
  apps/web-client/src/app/layout.tsx
  apps/web-client/src/app/lib/fetch.ts
  pnpm-lock.yaml
Labels: backend, frontend

#67 [AIEW-94] InterviewSession 상태별 수정 & 삭제 정책 구현
  apps/core-api/package.json
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/routes/warning/user/delete/index.ts
  apps/core-api/test/routes/api/v1/interviews.test.ts
  pnpm-lock.yaml
Labels: backend

#68 [AIEW-95] InterviewSession title의 unique 제약조건 보장
  apps/core-api/src/plugins/services/interview.ts
Labels: backend

#72 [AIEW-99] 면접 질문 제공 로직 통합
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/plugins/socket.ts
  apps/core-api/test/routes/ws/interview.ws.test.ts
  apps/core-api/test/services/interview.service.test.ts
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/InterviewerPannel.tsx
  apps/web-client/src/app/lib/socket/interviewStore.ts
  apps/web-client/src/app/lib/socket/types.ts
Labels: backend, frontend

#73 [AIEW-103] interviewing 화면 구현
  apps/web-client/next.config.ts
  apps/web-client/public/icons/exit.svg
  apps/web-client/public/icons/hourglass.svg
  apps/web-client/public/icons/lightbulb.svg
  apps/web-client/public/icons/mic.svg
  apps/web-client/public/icons/redo.svg
  apps/web-client/public/icons/toggle_false.svg
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/AnswerControl/AnswerButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/AnswerControl/AnswerControl.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/AnswerControl/AnswerTimer.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/AnswerControl/RedoButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel/HintSection.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel/Interviewee.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel/IntervieweePannel.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel/IntervieweeTranscript.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel/LeaveButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/IntervieweePannel/Questions.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/InterviewerPannel/InterviewHeader.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/InterviewerPannel/InterviewTimer.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/InterviewerPannel/Interviewer.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/InterviewerPannel/InterviewerPannel.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_comonents/InterviewerPannel/InterviewerSubtitle.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/page.tsx
Labels: frontend

#75 fix(ai): update evaluation model to remove tail question
  apps/ai-server/app/config/prompt/evaluation_prompt.txt
  apps/ai-server/app/config/prompt/followup_prompt.txt
  apps/ai-server/app/models/evaluation.py
  apps/ai-server/app/models/followup.py
  apps/ai-server/app/services/answer_evaluator.py
Labels: ai

#76 [AIEW-105] 답변 평가 API 재연결
  apps/core-api/package.json
  apps/core-api/prisma/migrations/20250921041217_add_feedback_to_interview_step/migration.sql
  apps/core-api/prisma/schema.prisma
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/types/ai.types.ts
Labels: backend

#77 [AIEW-72] 세션 평가 API 연결
  apps/core-api/src/plugins/services/ai-client.ts
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/plugins/socket.ts
  apps/core-api/src/types/ai.types.ts
Labels: backend

#71 [AIEW-79] 감정분석
  apps/ai-server/app/api/v1/endpoints/emotion.py
  apps/ai-server/app/config/prompt/evaluation_prompt.txt
  apps/ai-server/app/main.py
  apps/ai-server/app/models/emotion.py
  apps/ai-server/app/services/emotion_analyst.py
  apps/ai-server/app/utils/video_analysis.py
  apps/ai-server/app/vi.py
  apps/ai-server/poetry.lock
  apps/ai-server/pyproject.toml
Labels: ai

#78 [AIEW-100] 랭체인 메모리 리셋
  apps/core-api/src/plugins/services/ai-client.ts
  apps/core-api/src/plugins/services/interview.ts
Labels: backend

#74 [AIEW-101] TTS 세부 설정
  apps/core-api/src/plugins/services/tts.ts
Labels: backend

#80 [AIEW-108] interview 기능 고도화
  apps/web-client/public/icons/cancel.svg
  apps/web-client/public/icons/exit.svg
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/AnswerControl/AnswerButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/AnswerControl/AnswerControl.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/AnswerControl/AnswerTimer.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/AnswerControl/RedoButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/ExitLink.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/HintArea.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/HintButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/HintPannel.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/HintSection.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/IntervieweePannel.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/IntervieweeContainer/LeaveButton.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/InterviewerPannel/InterviewTimer.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/_components/InterviewerPannel/InterviewerPannel.tsx
  apps/web-client/src/app/(main)/interview/(socket)/[sessionId]/page.tsx
  apps/web-client/src/app/hooks/useAnswerControl.tsx
  apps/web-client/src/app/lib/answerStore.ts
  apps/web-client/src/app/lib/socket/interviewStore.ts
  apps/web-client/src/app/lib/socket/sttStore.ts
  apps/web-client/src/app/lib/socket/types.ts
Labels: frontend

#82 [AIEW-104] 면접 세션 진행 시간 & 답변 완료된 질문 리스트
  apps/core-api/prisma/migrations/20250928074748_add_timestamp_fields/migration.sql
  apps/core-api/prisma/schema.prisma
  apps/core-api/src/plugins/services/interview.ts
  apps/core-api/src/plugins/socket.ts
  apps/core-api/test/routes/ws/interview.ws.test.ts
  apps/core-api/test/services/interview.service.test.ts
Labels: backend

#84 [AIEW-112] CI에서만 발생하는 테스트 문제
  apps/core-api/test/routes/ws/interview.ws.test.ts
Labels: bug, backend, Infra
